const ActionType = {
  HEADER_TAB: 'HEADER_TAB',
  APP_MOBILE: 'APP_MOBILE',

  CART_BYER_INITIAL_DEAD:'CART_BYER_INITIAL_DEAD',
  CART_BYER_DATE_BERTHDAY:'CART_BYER_DATE_BERTHDAY',
  CART_BYER_DATE_DEAD:'CART_BYER_DATE_DEAD',
  CART_BYER_FILE:'CART_BYER_FILE',
  CART_INSTALL:'CART_INSTALL',
  CART_BYER_INITIAL:'CART_BYER_INITIAL',
  CART_BYER_TEL:'CART_BYER_TEL',
  CART_BYER_EMAIL:'CART_BYER_EMAIL',
  CART_COMENT:'CART_COMENT',
  CART_ADDRES_REGION:'CART_ADDRES_REGION',
  CART_ADDRES_CITY:'CART_ADDRES_CITY',
  CART_ADDRES:'CART_ADDRES',
  CART_ADDRES_INDEX:'CART_ADDRES_INDEX',
  CART_DELIVERY_METHOD:'CART_DELIVERY_METHOD',
  CART_PAY_METHOD:'CART_PAY_METHOD', 
  CART_CONSULT_BYER_INITIAL:'CART_CONSULT_BYER_INITIAL',
  CART_CONSULT_BYER_TEL:'CART_CONSULT_BYER_TEL',
  CART_CONSULT_COMENT:"CART_CONSULT_COMENT",
}

export default ActionType;